using DspicoThemeForms.Core.Constants;
using DspicoThemeForms.Core.Helper;
using Serilog;
using System.Diagnostics;

namespace DspicoThemeForms.Core.Runners;

/// <summary>
/// Provides functionality to execute the ptexconv tool with specified arguments and log its output and errors.
/// </summary>
/// <remarks>Use this class to run the ptexconv executable from a given path, capturing both standard output and
/// error messages via a provided logging delegate. The class checks for the existence of the executable and the
/// required tools directory before execution. If execution fails or required arguments are missing, appropriate log
/// messages are generated. This class is not thread-safe.</remarks>
public sealed class PtexConvRunner
{
    private string PtexConvPath { get; }

    public PtexConvRunner(string ptexConvPath)
    {
        if (!File.Exists(ptexConvPath))
            throw new FileNotFoundException("ptexconv executable not found at the specified path.", ptexConvPath);

        PtexConvPath = ptexConvPath;
    }

    /// <summary>
    /// Executes the ptexconv command-line tool with the specified arguments and returns a value indicating whether the
    /// operation completed successfully.
    /// </summary>
    /// <remarks>This method logs all output and error messages generated by the ptexconv process. A valid
    /// tools directory is required for execution. If the process fails or an exception occurs, the method returns
    /// false.</remarks>
    /// <param name="arguments">The command-line arguments to pass to the ptexconv tool. This parameter must not be null or empty.</param>
    /// <returns>true if the ptexconv command executed without errors; otherwise, false.</returns>
    public bool Run(string arguments)
    {
        bool HasError = false;
        try
        {
            if (string.IsNullOrEmpty(arguments))
            {
                Log.Warning("No arguments provided for ptexconv.");
                return false;
            }

            string toolsDir = PathHelper.GetToolsDirectory();
            if (string.IsNullOrEmpty(toolsDir))
            {
                Log.Warning("Tools directory not found.");
                return false;
            }

            Log.Information("Running ptexconv with arguments: " + arguments);
            ProcessStartInfo psi = new()
            {
                FileName = FilesContants.CmdExeName,
                WorkingDirectory = toolsDir,
                Arguments = $"/c {PtexConvPath} {arguments}",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using var proc = new Process { StartInfo = psi };
            proc.OutputDataReceived += (s, e) =>
            {
                if (!string.IsNullOrEmpty(e.Data))
                {
                    Log.Information(e.Data);
                }
            };

            proc.ErrorDataReceived += (s, e) =>
            {
                if (!string.IsNullOrEmpty(e.Data))
                {
                    Log.Error("ERROR:" + e.Data);
                    HasError = true;
                }
            };

            proc.Start();
            proc.BeginOutputReadLine();
            proc.BeginErrorReadLine();

            proc.WaitForExit();

            if (proc.ExitCode != 0)
            {
                throw new Exception($"ptexconv failed with exit code {proc.ExitCode}");
            }

            return !HasError;
        }
        catch (Exception ex)
        {
            Log.Error("Exception while running ptexconv: " + ex.Message);
            return false;
        }
    }
}

